language: python
services:
- docker
script:
- |
  changed=$(git diff --dirstat=files,0 HEAD~1 | awk '{ print $2 }')
  for dir_name in $(ls -d */ | sed s'/.$//')
  do
  if echo $changed | grep -w $dir_name > /dev/null; then
      (cd $dir_name && docker build -t tronwallet/$dir_name .)
  fi
  done
deploy:
  provider: script
  script: bash ci-deploy
  on:
    branch: master
env:
  global:
  - secure: RX4hQuc3XFaSsLZ5u5JebuqxbHwGZRBgLPfTA2jnY9XHIGkAEZAUUty83670MFvEvSG+PzXAk0z+WoPL2TE2Gp/qxwEXVyxO56yDB7eo/HzRqoqIHL+8Yhky49+7euSdAXVqmX2THp4IUnEW0QOJJ6F6usrCfnOioFpKYlRVHx/wDpYx1vbq4im+iXQMTZB8w6Aiy0fQHSvJz7RDUT6LgkBw9JOX6VmHjVqlTHqeItS8XqJGxvNkO/FPQGdX3tlPM+jft+NnPPCy8/HqQYmzcXxeU065uB3vL2/iIcwYJKa35EBI7UyMGYFRIga7REwD1Q5v3DG+UH+F8UeFydGjoSItuFcdWOVIv8eqldm3QhXf6au4DoVMLmQstkshHBWxvMkmYavDJixzrJJ0ARoKhhI0woSXMdMpoigi0o4JA2U0uymCRl3F33zul0mRTgR+nB60TVxiX+vTBcIkI2yUZI/0gB2YjE/6NrWD3ksp0RQEH+qz9X/5f17PB3rDsdZBOmDBkfHc4/GPPbbtPtxlYItLCxec4R4mIC6ikweN4ccprjVELhongk0YeGBRQRaPVKDxAiM9cAxD0hNQGt0QaSuo0nfFciyaZUn+4KnT81jYLMl/gieR7l+4ptrmApJhBqR5+TLvk3dnGT8ZjjpLNzEmLfrfMQALdhJBbLdF+Ks=
  - secure: NeSDus2jQfCmBQuik6/dnES7iKwU61Bl6CX/XVwX9YzVHujLWDBzNvztNv1Gr0EAOhIMmb+LDT5ba6T3/FT3cxB14pdltPeARnB3CtVbdWTSzrmqJGzdERmG5TJ+FzMKTdls4sS0Bn36Q8IKt23+cYEc5UNUbFK6jxWJIYz6sr8qMTzDYcTWJJl4YtidZsWa7l4wm1ftFiiIzG88LozpLG8jCAs9QyQtQmR865faeRVnemmOQhMlV/Gsr5cCJGKdSjp1TbD6p8GELUZkvEPSibdpmmb2wAZczwn2K+ZNp1VwMmht887C83GTrCKeA3t1ZwTGRrZBSyvEM//pHVlqJer0gvOL2xVZqJzGg+ldmreNC+NMLVMpn4YeODVKBfEiW0DuJ1wVFFkxEB2zSjEEm9KUPy6oCBB2MT37qIjzSpZImHMk4K18Pg6eHBqDP5899J8/pkNye0sjTKjr2jdPHyYa3EtFq45/JOpaSKZlab6IJnC3mVZlXV6H8UmooRmpVaDlU4TxJb8TXUWHjIPr3eY3RgAiB542T2N648ZTZ4NHOCqGpRazN8mVLB0+GETRlYj2lZ/BuHZKgOZ1CmZrtzk32bzp8dku9QlrVAP3jZEMXZH0/XzMeYSI/7TUWQYSdCh4uMML86RcYOrrT0Ed1sKAiP1VhbiK0SnFzAhbtvo=
