FROM golang:1.14-buster

# install OS dependencies and golangci-lint
RUN apt update \
    && apt install -y bash git make curl gcc g++ \
    && go get golang.org/x/lint/golint \
    && go get github.com/mitchellh/gox
